import type { Cut } from './types';

export const CUTS: Cut[] = [
  {
    id: 'tira',
    name: 'Short Ribs',
    local: 'Tira de asado',
    kind: 'beef',
    tier: 'slow',
    perPersonKg: 0.4,
    minutes: 75,
    targetTempC: 68,
    prep: 'Thick coarse salt 40 min before. Room temp. Never wash.',
    signals: ['Fat turns glassy', 'Meat pulls back off the bone', 'Bark is dark, no sheen'],
    rotateRule: 'Do not touch for the first 20 min. Turn when the underside releases on its own.',
    pullRule: 'Around 68°C and the bones show — probe-tender. It keeps cooking off the fire.',
    restMin: 10,
    carve: 'Cut across the bones into strips, short side up.',
  },
  {
    id: 'bife-chorizo',
    name: 'Sirloin Strip',
    local: 'Bife de chorizo',
    kind: 'beef',
    tier: 'medium',
    perPersonKg: 0.3,
    minutes: 40,
    targetTempC: 55,
    prep: 'Salt right before the fire. Thick cut, NY-strip shape.',
    signals: ['Surface seared, juicing slows', 'Edges curl up from the grate'],
    rotateRule: 'Sear one side until it releases, then rotate a quarter turn for crosshatch.',
    pullRule: '55°C center for medium-rare before rest. Carry-over adds ~3°C.',
    restMin: 8,
    carve: 'Slice against the grain, thumb-thick, across the strip.',
  },
  {
    id: 'bife-ancho',
    name: 'Ribeye',
    local: 'Bife ancho',
    kind: 'beef',
    tier: 'medium',
    perPersonKg: 0.3,
    minutes: 40,
    targetTempC: 57,
    prep: 'Rest at room temp, salt it 30 min out.',
    signals: ['Cap feels soft yet springs back', 'Fat at the edge renders, starts to crisp'],
    rotateRule: 'Roll it on its fat edge for 1–2 min once the faces are seared.',
    pullRule: '57°C center. The cap should be tender, not wobbly.',
    restMin: 8,
    carve: 'Slice against the grain across the eye.',
  },
  {
    id: 'entrana',
    name: 'Skirt Steak',
    local: 'Entraña',
    kind: 'beef',
    tier: 'medium',
    perPersonKg: 0.25,
    minutes: 30,
    targetTempC: 55,
    prep: 'Dry it well, salt both sides just before fire.',
    signals: ['Crust forms fast — it is thin', 'Juice beads stop running clear'],
    rotateRule: 'One fast sear per side. Thin cut: no fiddling.',
    pullRule: 'Springy to the poke, 55°C. It tightens quickly past that.',
    restMin: 5,
    carve: 'Along the fibers first, then slice across — it needs the cross-cut.',
  },
  {
    id: 'vacio',
    name: 'Flank',
    local: 'Vacío',
    kind: 'beef',
    tier: 'slow',
    perPersonKg: 0.35,
    minutes: 60,
    targetTempC: 60,
    prep: 'The membrane side goes down first — leave its fat cap on.',
    signals: ['Crust cracks like glass', 'Inside stays pink while outside darkens'],
    rotateRule: 'Low heat, patient. Rotate for even browning, never rush it.',
    pullRule: '60°C and the crust is a hard shell. Rest long.',
    restMin: 10,
    carve: 'Across the grain into wide fajita-style strips.',
  },
  {
    id: 'costilla',
    name: 'Whole Rib Rack',
    local: 'Costillar',
    kind: 'beef',
    tier: 'slow',
    perPersonKg: 0.35,
    minutes: 210,
    targetTempC: 70,
    prep: 'A full rack is a centerpiece — salt the fat side only.',
    signals: ['Skin crisps gradually', 'Bone ends darken and release'],
    rotateRule: 'Indirect heat zone. Rotate the rack every 40 min, thin end toward the glow.',
    pullRule: 'When the short bones bend and the meat sags — 70°C is done, not dry.',
    restMin: 15,
    carve: 'Cut into individual ribs at the table.',
  },
  {
    id: 'pollo',
    name: 'Chicken Quarters',
    local: 'Pollo',
    kind: 'other',
    tier: 'medium',
    perPersonKg: 0.3,
    minutes: 50,
    targetTempC: 75,
    prep: 'Butterfly or press flat. Salt and olive oil before fire.',
    signals: ['Skin contracts and blisters', 'Clear juices from the deepest poke'],
    rotateRule: 'Skin side away from the hottest coals first, flip when golden.',
    pullRule: '75°C at the thickest joint. Never serve pink near the bone.',
    restMin: 5,
    carve: 'Separate thigh and leg at the joint.',
  },
  {
    id: 'cordero',
    name: 'Lamb Leg',
    local: 'Cordero',
    kind: 'other',
    tier: 'slow',
    perPersonKg: 0.4,
    minutes: 120,
    targetTempC: 62,
    prep: 'Patagonian style: salt crust, rosemary optional.',
    signals: ['Surface turns mahogany', 'Leg pulls from the bone tip'],
    rotateRule: 'Rotate continuously over low coals, slow roast wins here.',
    pullRule: '62°C for pink middle, more if the crowd likes it done.',
    restMin: 12,
    carve: 'Slice thin across the muscle.',
  },
  {
    id: 'matambre',
    name: 'Rolled Flank',
    local: 'Matambre',
    kind: 'beef',
    tier: 'medium',
    perPersonKg: 0.25,
    minutes: 45,
    targetTempC: 65,
    prep: 'If rolled with stuffing, tie snug and cook indirect.',
    signals: ['Roll tightens and steams', 'Outer layer turns deep brown'],
    rotateRule: 'Rotate the roll a quarter turn every 10 min for even walls.',
    pullRule: '65°C through the center.',
    restMin: 8,
    carve: 'Cut coins, then rest each coin against the grain.',
  },
  {
    id: 'chorizo',
    name: 'Criollo Sausage',
    local: 'Chorizo',
    kind: 'achura',
    tier: 'fast',
    perPersonKg: 0.0,
    unitPerPeople: 2,
    minutes: 25,
    targetTempC: 70,
    prep: 'Place where embers are rippling, not roaring.',
    signals: ['Skin tightens, juices seep out visibly', 'Char in spots is good'],
    rotateRule: 'Turn every 8 min, no piercing to "help the fat".',
    pullRule: 'No pink center — 70°C. Juicy means juicy, not raw.',
    restMin: 3,
    carve: 'Angle-cut coins or split for a sandwich (choripán).',
  },
  {
    id: 'morcilla',
    name: 'Blood Sausage',
    local: 'Morcilla',
    kind: 'achura',
    tier: 'fast',
    perPersonKg: 0.0,
    unitPerPeople: 3,
    minutes: 20,
    targetTempC: 70,
    prep: 'Do not prick it. Dark thin casing, low heat.',
    signals: ['Tiny fat pearls on the skin', 'It plumps without splitting'],
    rotateRule: 'Turn gently with tongs — a split casing leaks everything.',
    pullRule: 'Off the fire just before the skin gets ready to crack.',
    restMin: 2,
    carve: 'Halve lengthwise.',
  },
  {
    id: 'mollejas',
    name: 'Sweetbreads',
    local: 'Mollejas',
    kind: 'achura',
    tier: 'fast',
    perPersonKg: 0.1,
    minutes: 25,
    targetTempC: 0,
    prep: 'Whole — never cut them up before the fire.',
    signals: ['Crisp caramel shell outside', 'Interior still custard-soft'],
    rotateRule: 'Pressure with the spatula for an even crust, flip once.',
    pullRule: 'Dark crust, molten center. Undercooked inside is wrong — it must set.',
    restMin: 3,
    carve: 'Slice thick, serve on warm bread.',
  },
  {
    id: 'chinchulines',
    name: 'Chitterlings',
    local: 'Chinchulines',
    kind: 'achura',
    tier: 'fast',
    perPersonKg: 0.0,
    unitPerPeople: 4,
    minutes: 25,
    targetTempC: 0,
    prep: 'Best pre-boiled in salted water 30 min — the short path to tender.',
    signals: ['They curl and tighten', 'Edges blister and crisp'],
    rotateRule: 'High heat first, rotate until evenly coiled and curled.',
    pullRule: 'Snappy, not leathery. Low heat from then on.',
    restMin: 2,
    carve: 'Serve whole, salted at the table.',
  },
  {
    id: 'provoleta',
    name: 'Provolone Wheel',
    local: 'Provoleta',
    kind: 'achura',
    tier: 'fast',
    perPersonKg: 0.0,
    unitPerPeople: 5,
    minutes: 12,
    targetTempC: 0,
    prep: 'Slice 2–3 cm thick, oregano + pepper on top.',
    signals: ['Edges blister brown', 'Middle goes molten and shrugs'],
    rotateRule: 'Do not move it — the browned base is the point.',
    pullRule: 'Charr base, lava center. Slide off onto bread, do not flip.',
    restMin: 1,
    carve: 'Eat with the spoon straight off the board.',
  },
];

export const CUT_MAP: Record<string, Cut> = Object.fromEntries(
  CUTS.map((cut) => [cut.id, cut]),
);

export const BEEF_DEFAULTS = ['tira', 'bife-chorizo', 'vacio'];

export const FUELS = [
  {
    id: 'wood',
    label: 'Wood',
    local: 'Leña / quebracho',
    buildMin: 50,
    rateKgH: 1.8,
    hint: 'Hardwood only — quebracho, espinillo. Smokier, slower, worth it.',
  },
  {
    id: 'charcoal',
    label: 'Charcoal',
    local: 'Carbón',
    buildMin: 30,
    rateKgH: 1.1,
    hint: 'The weekday, dependable choice. Lump charcoal, never briquettes.',
  },
  {
    id: 'gas',
    label: 'Gas',
    local: 'Gas',
    buildMin: 5,
    rateKgH: 0,
    hint: 'Zero romance, instant control. Fine for steaks and weeknights.',
  },
] as const;